name: Resolve Issue with LLMOps Resolver

on:
  issues:
    types: [labeled]

env:
  PAT_TOKEN: ${{ secrets.PAT_TOKEN }}

jobs:
  call-llmops-resolver:
    permissions:
      contents: write
      pull-requests: write
      issues: write
    if: ${{ github.event.label.name == 'assigned-to-llmops-issue-resolver' }} 
    uses: 'BrunoScaglione/llmops-issue-resolver/.github/workflows/llmops-issue-resolver.yml@main'
    with:
      issue_number: ${{ github.event.issue.number }}
      repository_name: ${{ github.repository }}